mongo-url = "mongodb://admin:qwer1234!@mongodb:27017/damoa?authSource=admin"
elasticsearch-urls = ["http://elasticsearch:9200"]
enable-oplog = true

# 완전한 매핑 설정
[[mapping]]
namespace = "damoa.kakao_product"
index = "kakao_product"